name: First Test on AWS

on:
  push:
    branches:
      - main


jobs:

  job1:
    runs-on: ubuntu-latest # macos-latest, windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # some of the inbuilt functions, provided by github for doing some common tasks. checkout means make a copy of the code from the repo

      - name: Install Python-3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      
      - name: Run tests
        run: pytest
          

      
    